name: Build

on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init submodule
      run: |
        git submodule update --init --recursive

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        cd ./Maverick
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Get build cache
    # - uses: actions/checkout@v2
    #   with:
    #     ref: 'cache'
    #     path: './build_cache'

    - name: Build site
      run: |
        python ./Maverick/mvrk.py --config ./config.py

    - name: Deploy to GitHub Pages
      uses: docker://peaceiris/gh-pages:v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: main
        PUBLISH_DIR: ./dist
      with:
        emptyCommits: false

    # - name: Save build cache
    #   uses: docker://peaceiris/gh-pages:v2
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     PUBLISH_BRANCH: cache
    #     PUBLISH_DIR: ./build_cache
    #   with:
    #     emptyCommits: false
